#! /bin/bash -x
random1=$((RANDOM%(99)+1))
random2=$((RANDOM%(99)+1))
random3=$((RANDOM%(99)+1))
random4=$((RANDOM%(99)+1))
random5=$((RANDOM%(99)+1))

AVG_CONSTANT=5

sum=$((random1+random2+random3+random4+random5))
echo=$sum

average=$((sum/AVG_CONSTANT))
echo=$average
